### ISSUE TITLE
Roadmap zu Semantic Versioning

### ISSUE THREAD

**Issue by jmaedler** [martinkosch/Open62541.jl#30]
Hi @martinkosch, hi @thomvet,

I am currently working on a framework using OPC UA to integrate soft-controllers and [ModelingToolkit.jl](https://github.com/SciML/ModelingToolkit.jl) for virtual commissioning. Thus, I was searching for an OPC UA package in Julia and found yours. That does currently work just fine for me, but I was wondering if there is any roadmap to bring this package to semantic versioning, because we want to use it for virtual commisioning in our Start-Up on modular process plants. What else do you want to do before you start with semantic versioning? I am not very experienced in working on Github (so far), but I would try to contribute to the package. Feel free to answer here or send me a message on [Discourse](https://discourse.julialang.org/) or an email.

Best, Jonathan

**Comment by thomvet** [comment]
Hi Jonathan,
Thanks for your interest in this package. The good news is that we are already committed to semantic versioning, meaning that we will increase x in 0.x whenever we introduce a breaking change. 

**However**, since we haven't really settled on the public API yet (apart from re-exporting open62541's API!), breaking changes might occur at a "frequent" pace. As long as you set appropriate compat bounds in ModelingToolkit.jl's Project.toml, we'll (probably/hopefully!) not break your stuff due to it.

I wanted to push out a new version of the package already a few weeks back (see [the open PR](https://github.com/martinkosch/Open62541.jl/pull/29)), but I got held up at my "day job".  If I were you, I would wait for that version before formally adopting it, because it's also upping the version of open62541 (the C-library) to 1.4.x, which is the current release branch. It's not too far away, because all that's left to do are doc improvements & cosmetics. I'll get it done soon. 

For what it's worth, I do already use the Open62541.jl package to control devices in my lab, which is part of a pharma company's R&D. It's working well _for that purpose_. That said, I would, as the readme also says, not advise to use it in a production environment where a day's loss of work can mean a significant financial loss...

I'll open a separate issue about "how to contribute".

Best,
Thomas

**Comment by jmaedler** [comment]
Hi Thomas, 

thank you very much for your explanations! That helps me a lot! 

For the time being, we will really only use the package for virtual commissioning. So the risk of major financial damage is quite limited for now :-D . I will continue to develop initial concepts based on the current version of the package. I'm looking forward to the new version and your issue on “how to contribute”.

Best,
Jonathan

**Comment by thomvet** [comment]
Hi @jmaedler, 
Good news. I finally got around to putting some work into this.
I have merged that pull request and also tried outlining how one could contribute to developing this further here: https://github.com/martinkosch/Open62541.jl/issues/32

Other ideas/directions are of course also welcome!
